version: "3.2"
services:
  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    container_name: "rabbitmq"
    ports:
      - 5673:5672
      - 15673:15672
  consumer:
    image: consumer
    ports:
      - 7500:7500
    depends_on:
      - "rabbitmq"
    environment:
      AMQP_URL: amqp://rabbitmq:5672
      PORT: 7500
    producer:
    image: producer
    ports:
      - 6969:6969
    depends_on:
      - "rabbitmq"
    environment:
      AMQP_URL: amqp://rabbitmq:5672
      PORT: 6969
    command: sh -c '/bin/wait-for-it.sh rabbitmq:5672 --timeout=30 -- node producer.js'
