version: "3.2"
services:
  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    container_name: "rabbitmq"
    ports:
      - 5673:5672
      - 15673:15672
  
  nitish:
    image: postgres:latest
    environment:
          - POSTGRES_USER=srini
          - POSTGRES_PASSWORD=wasd
          - POSTGRES_DB=cc
    ports:
      - 5433:5432
  database:
    image: database
    ports:
      - 4000:4000
    environment:
      AMQP_URL: amqp://rabbitmq:5672
      PORT: 4000
      DATABASE_URL: postgresql://srini:wasd@nitish:5432/cc

    command: sh -c './delay.sh rabbitmq:5672 --timeout=30 -- npx prisma migrate deploy && node db.js'
    
  consumer1:
    image: consumer
    container_name: "Rajendra_prasad"
    ports:
      - 7500:7500
    depends_on:
      - "rabbitmq"
    environment:
      AMQP_URL: amqp://rabbitmq:5672
      PORT: 7500
      
    command: sh -c './delay.sh rabbitmq:5672 --timeout=30 -- node consumer.js'
  
  consumer2:
    image: consumer
    container_name: "Bishwajith_Ray"
    ports:
      - 7501:7501
    depends_on:
      - "rabbitmq"
    environment:
      AMQP_URL: amqp://rabbitmq:5672
      PORT: 7501
      
    command: sh -c './delay.sh rabbitmq:5672 --timeout=30 -- node consumer.js'
  producer:
    image: producer
    ports:
      - 6969:6969
    depends_on:
      - "rabbitmq"
    environment:
      AMQP_URL: amqp://rabbitmq:5672
      PORT: 6969
    command: sh -c './delay.sh rabbitmq:5672 --timeout=30 -- node producer.js'
